train:
  dataset_path: "data/processed/v2_air_quality.csv"
  target_column: "AQI"

  test_size: 0.2
  random_state: 42

  # Модель, которую используем для обучения
  model_type: "random_forest"   # варианты: linear, random_forest, lightgbm

  # Гиперпараметры моделей
  linear:
    fit_intercept: true

  random_forest:
    n_estimators: 200
    max_depth: 10

  lightgbm:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: -1

inference:
  model_path: "models/model.joblib"
  features_path: "models/features.json"
